#!/usr/bin/env bash
# Bash script that takes a path, and confirms if it is a directory or not. If it is a directory list all files in that directory,
# if not ask the user to give the file path of a directory. 

# Prompt user for path & read
echo "Enter Path To Directory:"
read user_path

# Check validity
if [ ! -d "$user_path" ]; then
    echo "Enter A Valid Path:"
else
    ls "$user_path"
fi
